### Numpy Task

In [2]:
import numpy as np

# 1~10까지의 요소를 ndarray에 담는다.
print("Q1.")
ndarray1 = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
print(ndarray1, ndarray1.dtype)

Q1.
[ 1  2  3  4  5  6  7  8  9 10] int32


In [93]:
# 3행 2열 list를 ndarray에 담고, 각 요소는 순서대로 6, 5, 4, 3, 2, 1이다.
print("Q2.")
ndarray1 = np.array([[6, 5], [4, 3], [2, 1]])
print(ndarray1)

Q2.
[[6 5]
 [4 3]
 [2 1]]


In [3]:
# 4행 1열 ndarray, 순서대로 10, 8, 6, 4를 담는다.
# Transpose: 전치. 행과 열을 바꿔준다.
print("Q3.")
# ndarray1 = np.array([[10], [8], [6], [4]])
ndarray1 = np.array([[(5 - i) * 2 for i in range(4)]]).T
print(ndarray1)

Q3.
[[10]
 [ 8]
 [ 6]
 [ 4]]


In [95]:
# 1~10까지의 요소를 ndarray에 담고, 각 요소에 5씩 더해준다.
print("Q4.")
ndarray1 = np.arange(1, 11)
print([i + 5 for i in ndarray1])

Q4.
[6, 7, 8, 9, 10, 11, 12, 13, 14, 15]


In [4]:
# axis 0이 10인 shape이면서 모든 원소가 0, dtype은 int32인 ndarray를 만든다.
print("Q5.")
ndarray1 = np.zeros(10,) # 기본 타입 - float64
ndarray2 = ndarray1.astype(np.int32)
print(ndarray2, ndarray2.dtype, ndarray2.shape)

Q5.
[0 0 0 0 0 0 0 0 0 0] int32 (10,)


In [98]:
# axis 0이 5, 각 요소기 0~4인 ndarray를 만든다.
print("Q6.")
ndarray1 = np.arange(0, 5)
print(ndarray1, ndarray1.shape)

Q6.
[0 1 2 3 4] (5,)


In [6]:
# 아래의 ndarray1이 주어졌을 때 순서대로 문제를 해결한다.
ndarray1 = np.arange(0, 16)

# 2 Dimension, axis 1은 2로 변경
print("Q7.")
ndarray1_axis1_2 = ndarray1.reshape((-1, 2)) # -1: 자동 연산
print(ndarray1_axis1_2)

Q7.
[[ 0  1]
 [ 2  3]
 [ 4  5]
 [ 6  7]
 [ 8  9]
 [10 11]
 [12 13]
 [14 15]]


In [8]:
# 2 Dimension, axis 0은 8로 변경
print("Q8.")
ndarray1_axis0_8 = ndarray1.reshape((8, -1))
print(ndarray1_axis0_8)

Q8.
[[ 0  1]
 [ 2  3]
 [ 4  5]
 [ 6  7]
 [ 8  9]
 [10 11]
 [12 13]
 [14 15]]


In [7]:
# 3 Dimension으로 변경
print("Q8.")
ndarray3 = ndarray1.reshape((2, 2, -1))
print(ndarray3)

Q8.
[[[ 0  1  2  3]
  [ 4  5  6  7]]

 [[ 8  9 10 11]
  [12 13 14 15]]]


In [102]:
# ndarray3을 axis 1이 1인 2차원 ndarray로 변환
print("Q9.")
ndarray3_2d = ndarray3.reshape((-1, 1))
print(ndarray3_2d)

Q9.
[[ 0]
 [ 1]
 [ 2]
 [ 3]
 [ 4]
 [ 5]
 [ 6]
 [ 7]
 [ 8]
 [ 9]
 [10]
 [11]
 [12]
 [13]
 [14]
 [15]]


In [103]:
# ndarray3을 1 Dimension으로 변환
print("Q10.")
ndarray3_1d = ndarray3.reshape((-1, ))
print(ndarray3_1d)

Q10.
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]


In [137]:
# 1차원 ndarray 1~100까지 값 중 97 추출
print("Q11.")
ndarray1 = np.arange(1, 101)
ndarray1_97 = ndarray1[ndarray1 == 97]

print(ndarray1_97)

Q11.
[97]


In [105]:
# 아래의 ndarray1이 주어졌을 때 순서대로 문제를 해결한다.
ndarray1 = np.arange(1, 21)

# 2차원 배열 axis 0은 4, axis 1은 5로, 1~20의 값 중 15 추출
print("Q12.")
ndarray1_2d = ndarray1.reshape((4, 5))
ndarray1_2d_15 = ndarray1_2d[ndarray1_2d == 15]

print(ndarray1_2d_15)

Q12.
[15]


In [106]:
# 2 Dimension, axis 0은 5로 변경
print("Q13.")
ndarray1_axis0_5 = ndarray1.reshape((5, -1))

print(ndarray1_axis0_5)

Q13.
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]
 [17 18 19 20]]


In [107]:
# 2번째 행의 4번째 숫자 출력
print("Q14.")
ndarray1_axis0_5_13 = ndarray1_axis0_5[1, 3]

print(ndarray1_axis0_5_13)

Q14.
8


In [108]:
# 1~100 중 짝수만 출력
print("Q15.")
ndarray1 = np.arange(start=2, stop=101, step=2)

print(ndarray1)

Q15.
[  2   4   6   8  10  12  14  16  18  20  22  24  26  28  30  32  34  36
  38  40  42  44  46  48  50  52  54  56  58  60  62  64  66  68  70  72
  74  76  78  80  82  84  86  88  90  92  94  96  98 100]


In [115]:
# 위에서 구한 짝수들을 axis 0이 10인 2차원 배열로 변환 후, 82~100까지 추출
print("Q16.")
ndarray2 = ndarray1.reshape((10, -1))
print("2차원 배열")
print(ndarray2, end="\n\n")

ndarray2_sorted = ndarray2[-2:]

print("추출 후 배열")
print(ndarray2_sorted)

Q16.
2차원 배열
[[  2   4   6   8  10]
 [ 12  14  16  18  20]
 [ 22  24  26  28  30]
 [ 32  34  36  38  40]
 [ 42  44  46  48  50]
 [ 52  54  56  58  60]
 [ 62  64  66  68  70]
 [ 72  74  76  78  80]
 [ 82  84  86  88  90]
 [ 92  94  96  98 100]]

추출 후 배열
[[ 82  84  86  88  90]
 [ 92  94  96  98 100]]


In [147]:
# 위에서 구한 요소 중 (86, 100) 좌표 구하기
print("Q17.")

# 각 요소의 좌표
location86 = 0, 2
location100 = 1, 4

# ndarray2_sorted에서 특정 좌표에 있는 값 - 86, 100
eighty_six = ndarray2_sorted[location86]
hundred = ndarray2_sorted[location100]

print(f'{eighty_six}의 위치: {list(location86)}')
print(f'{hundred}의 위치: {list(location100)}')

Q17.
86의 위치: [0, 2]
100의 위치: [1, 4]


In [9]:
# 아래의 ndarray1이 주어졌을 때 순서대로 문제를 해결한다.
ndarray1 = np.arange(1, 101)

# 각 요소 중 1의 자리수가 2인 수들만 추출
print("Q18.")
ndarray2 = ndarray1[ndarray1 % 10 == 2]

print(ndarray2)

Q18.
[ 2 12 22 32 42 52 62 72 82 92]


In [119]:
# 1~49의 요소 중 2와 5의 공배수만 추출
print("Q19.")
ndarray3 = ndarray1[ndarray1 < 50]

print("1~49까지의 배열")
print(ndarray3, end="\n\n")

ndarray3_sorted = ndarray3[(ndarray3 % 2 == 0) & (ndarray3 % 5 == 0)]

print("2와 5의 공배수")
print(ndarray3_sorted)

Q19.
1~49까지의 배열
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48
 49]

2와 5의 공배수
[10 20 30 40]


In [120]:
# 위에서 추출한 공배수 중 20 이상인 값만 추출
print("Q20.")
ndarray3_resorted = ndarray3_sorted[ndarray3_sorted >= 20]

print(ndarray3_resorted)

Q20.
[20 30 40]


In [148]:
# 데이터를 분석하여, 각 수치별 오름차순 및 내림차순 후 이름을 출력하세요.
# [[과일이름], [가격]], 가격별 내림차순
array1 = [['Mango', 'Apple', 'Pear', 'Peach', 'Melon'], [1500, 1800, 2000, 2500, 8500]]

print("Q21.")

# 과일 배열 추출 - numpy.ndarray 타입으로 바꿔야 팬시 인덱싱 사용 가능
fruits = np.array(array1[0])
# print(fruits, type(fruits))

# 가격 배열 추출
prices = array1[1]
# print(prices)

prices_rank = np.argsort(prices)[::-1]
# print(prices_rank)

print(f'가격별 내림차순 정렬 된 과일 리스트: {fruits[prices_rank]}')

Q21.
가격별 내림차순 정렬 된 과일 리스트: ['Melon' 'Peach' 'Pear' 'Apple' 'Mango']


In [144]:
# [[이름], [나이], [학점]], 나이별 내림차순, 학점별 오름차순
array2 = [['둘리', '또치', '길동', '도너', '마이콜'], [7, 9, 40, 5, 20], ['C', 'A', 'B', 'F', 'D']]

print("Q22.")

# 학생 리스트 - numpy.ndarray 타입
students = np.array(array2[0])

# 나이 리스트
ages = array2[1]

# 나이 리스트 정렬 순서
age_rank = np.argsort(ages)[::-1]

# 학점 리스트
grades = array2[2]

# 학점 리스트 정렬 순서
grade_rank = np.argsort(grades)

print(f'나이별 내림차순으로 정렬된 학생들: {students[age_rank]}')
print(f'등급별 오름차순으로 정렬된 학생들: {students[grade_rank]}')

Q22.
나이별 내림차순으로 정렬된 학생들: ['길동' '마이콜' '또치' '둘리' '도너']
등급별 오름차순으로 정렬된 학생들: ['또치' '길동' '둘리' '마이콜' '도너']


In [133]:
# [[국가이름], [GDP 성장률]], GDP 성장률별 오름차순
array3 = [['한국', '영국', '러시아', '남아프리카 공화국', '미국'], ['1.7%', '-0.6%', '0.3%', '1.2%', '1.4%']]

# 국가 리스트 - numpy.ndarray 타입
countries = np.array(array3[0])

# GDP 성장률 리스트
gdp_growth = array3[1]

# GDP 성장률 리스트 정렬 순서
gdp_growth_rank = np.argsort(gdp_growth)
# print(gdp_growth_rank)

print(f'GDP 성장률별 오름차순으로 정렬된 국가들: {countries[gdp_growth_rank]}')

GDP 성장률별 오름차순으로 정렬된 국가들: ['영국' '러시아' '남아프리카 공화국' '미국' '한국']
